In [60]:
import main
import main_minerva
import pandas as pd
# Load event data for both teams (replace with actual file paths)
df_team1 = pd.read_csv('PunjabFC_vs_Minerva_U15_PunjabFC_data.csv')
df_team2 = pd.read_csv('PunjabFC_vs_Minerva_U15_Minerva_data.csv')
df1 = main.process_data(df_team1)
df2 = main.process_data(df_team2)
df1

,Team,Time,Jersey,Player,Event,X,Y,endX,endY,Foot,Outcome,Key Pass,Assist,Through Pass,Clearance,Take On,Hand Foul,Goal Area
0,Punjab FC,03:30,9,Gunleiba Wangkheirakpam,Pass,60,39,28,30,NaN,Complete,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Punjab FC,03:36,4,Shubham Poonia,Long Kick,23,28,53,24,NaN,Complete,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Punjab FC,03:39,22,Mahesh Meitei,Touch,50,22,0,0,NaN,Bad,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Punjab FC,03:46,22,Mahesh Meitei,Pressure,86,27,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Punjab FC,03:56,11,Thongbam Singh,Pressure,69,72,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
381,Punjab FC,100:51,6,Khuraijam Meetei,Pass,76,54,47,57,NaN,Complete,NaN,NaN,NaN,NaN,NaN,NaN,NaN
382,Punjab FC,100:54,3,Telem Singh,Long Kick,50,59,85,64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
383,Punjab FC,100:58,3,Telem Singh,Air Duel,54,61,0,0,NaN,Won,NaN,NaN,NaN,NaN,NaN,NaN,NaN
384,Punjab FC,101:42,3,Telem Singh,Goal Kick,8,48,8,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
385,Punjab FC,102:14,1,Aadil,Save,4,38,0,0,Left,Saved,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
mins_df1 = main.mins_secs(df1)
mins_df2 = main.mins_secs(df2)
mins_df2

,Team,Time,Jersey,Player,Event,X,Y,endX,endY,Foot,Outcome,Key Pass,Assist,Through Pass,Clearance,Take On,Hand Foul,Goal Area,Minutes,Seconds
0,Minerva FC,03:36,34,Loitam Mangal Singh,Pressure,87.0,50.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,36
1,Minerva FC,03:39,19,Jayed,Offensive Duel,74.0,62.0,0,0,NaN,Won,NaN,NaN,NaN,NaN,True,NaN,NaN,3,39
2,Minerva FC,03:41,19,Jayed,Offensive Duel,67.0,64.0,0,0,NaN,Won,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,41
3,Minerva FC,03:42,19,Jayed,Pass,68.0,57.0,38,63,NaN,Complete,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,42
4,Minerva FC,03:45,4,Sailex Oinam,Pass,47.0,64.0,14,47,NaN,Complete,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,Minerva FC,102:01,2,Ngashepam Reoson Singh,Pass,72.0,72.0,86,58,NaN,Complete,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102,1
700,Minerva FC,102:04,9,Raj Singh Wahengbam,Pass,82.0,63.0,101,74,NaN,Complete,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102,4
701,Minerva FC,102:12,44,Muhammed Ziyad K,Pass,87.0,69.0,96,52,NaN,Complete,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102,12
702,Minerva FC,102:12,14,Malsom Tuboi,Shot,105.0,54.0,116,42,Right,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Right,102,12
703,Minerva FC,102:43,9,Raj Singh Wahengbam,Corner,116.0,78.0,110,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102,43

In [62]:
team1 = main.add_passer_recipient_columns(mins_df1)
team2 = main.add_passer_recipient_columns(mins_df2)
team2

,Team,Time,Jersey,Player,Event,X,Y,endX,endY,Foot,...,Assist,Through Pass,Clearance,Take On,Hand Foul,Goal Area,Minutes,Seconds,Recipient,Passer
0,Minerva FC,03:36,34,Loitam Mangal Singh,Pressure,87.0,50.0,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3,36,NaN,NaN
1,Minerva FC,03:39,19,Jayed,Offensive Duel,74.0,62.0,0,0,NaN,...,NaN,NaN,NaN,True,NaN,NaN,3,39,NaN,NaN
2,Minerva FC,03:41,19,Jayed,Offensive Duel,67.0,64.0,0,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3,41,NaN,NaN
3,Minerva FC,03:42,19,Jayed,Pass,68.0,57.0,38,63,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3,42,4.0,19.0
4,Minerva FC,03:45,4,Sailex Oinam,Pass,47.0,64.0,14,47,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3,45,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,Minerva FC,102:01,2,Ngashepam Reoson Singh,Pass,72.0,72.0,86,58,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,102,1,9.0,2.0
700,Minerva FC,102:04,9,Raj Singh Wahengbam,Pass,82.0,63.0,101,74,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,102,4,44.0,9.0
701,Minerva FC,102:12,44,Muhammed Ziyad K,Pass,87.0,69.0,96,52,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,102,12,14.0,44.0
702,Minerva FC,102:12,14,Malsom Tuboi,Shot,105.0,54.0,116,42,Right,...,NaN,NaN,NaN,NaN,NaN,Right,102,12,NaN,NaN
703,Minerva FC,102:43,9,Raj Singh Wahengbam,Corner,116.0,78.0,110,38,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,102,43,NaN,NaN

In [63]:
# Calculate goals for each team
team1_goals = main.calculate_goals(df_team1)
team2_goals = main.calculate_goals(df_team2)
team2_goals

1

In [64]:
# Assign win/loss based on goals
if team1_goals > team2_goals:
    df_team1['win'] = 1
    df_team1['lost'] = 0
    df_team2['win'] = 0
    df_team2['lost'] = 1
elif team2_goals > team1_goals:
    df_team1['win'] = 0
    df_team1['lost'] = 1
    df_team2['win'] = 1
    df_team2['lost'] = 0
else:
    # In case of a draw
    df_team1['win'] = 0
    df_team1['lost'] = 0
    df_team2['win'] = 0
    df_team2['lost'] = 0
    
player_stats1 = main.calculate_player_stats(df1)
player_stats2 = main.calculate_player_stats(df2)
player_stats2.head()

,Player,goals,assists,shots_ontarget,shots_offtarget,shotsblocked,drib_success,drib_unsuccess,keypasses,touches,...,offsides,saved_pen,missed_penalties,owngoals,win,lost,minutesPlayed,game_duration,goals_conceded,saves_made
0,Ahvas K,0,0.0,0,0,0,2,2,0.0,43,...,0,0,0,0,0,0,66,102,0,0
1,Jayed,0,0.0,0,0,0,4,1,0.0,59,...,1,0,0,0,0,0,73,102,0,0
2,Khangembem Gibash Meitei,0,0.0,0,0,1,4,1,0.0,33,...,0,0,0,0,0,0,26,102,0,0
3,Khwairakpam Yoihenba,0,0.0,0,0,0,0,0,0.0,29,...,0,0,0,0,0,0,95,102,1,1
4,Lairenjam Sanathoi Meitei,0,0.0,0,0,0,6,0,0.0,43,...,2,0,0,0,0,0,66,102,0,0

In [65]:
player_stats1['is_home_team'] = 1 # home team
player_stats2['is_home_team'] = 0 # away team
player_stats2.head()

,Player,goals,assists,shots_ontarget,shots_offtarget,shotsblocked,drib_success,drib_unsuccess,keypasses,touches,...,saved_pen,missed_penalties,owngoals,win,lost,minutesPlayed,game_duration,goals_conceded,saves_made,is_home_team
0,Ahvas K,0,0.0,0,0,0,2,2,0.0,43,...,0,0,0,0,0,66,102,0,0,0
1,Jayed,0,0.0,0,0,0,4,1,0.0,59,...,0,0,0,0,0,73,102,0,0,0
2,Khangembem Gibash Meitei,0,0.0,0,0,1,4,1,0.0,33,...,0,0,0,0,0,26,102,0,0,0
3,Khwairakpam Yoihenba,0,0.0,0,0,0,0,0,0.0,29,...,0,0,0,0,0,95,102,1,1,0
4,Lairenjam Sanathoi Meitei,0,0.0,0,0,0,6,0,0.0,43,...,0,0,0,0,0,66,102,0,0,0

In [66]:
# Calculate goals for each team
team1_goals = main.calculate_goals(df_team1)
team2_goals = main.calculate_goals(df_team2)

# Assign win/loss based on goals
if team1_goals > team2_goals:
    player_stats1['win'] = 1
    player_stats1['lost'] = 0
    player_stats2['win'] = 0
    player_stats2['lost'] = 1
elif team2_goals > team1_goals:
    player_stats1['win'] = 0
    player_stats1['lost'] = 1
    player_stats2['win'] = 1
    player_stats2['lost'] = 0
else:
    # In case of a draw
    player_stats1['win'] = 0
    player_stats1['lost'] = 0
    player_stats2['win'] = 0
    player_stats2['lost'] = 0

player_stats2

,Player,goals,assists,shots_ontarget,shots_offtarget,shotsblocked,drib_success,drib_unsuccess,keypasses,touches,...,saved_pen,missed_penalties,owngoals,win,lost,minutesPlayed,game_duration,goals_conceded,saves_made,is_home_team
0,Ahvas K,0,0.0,0,0,0,2,2,0.0,43,...,0,0,0,0,0,66,102,0,0,0
1,Jayed,0,0.0,0,0,0,4,1,0.0,59,...,0,0,0,0,0,73,102,0,0,0
2,Khangembem Gibash Meitei,0,0.0,0,0,1,4,1,0.0,33,...,0,0,0,0,0,26,102,0,0,0
3,Khwairakpam Yoihenba,0,0.0,0,0,0,0,0,0.0,29,...,0,0,0,0,0,95,102,1,1,0
4,Lairenjam Sanathoi Meitei,0,0.0,0,0,0,6,0,0.0,43,...,0,0,0,0,0,66,102,0,0,0
5,Loitam Mangal Singh,0,0.0,0,0,0,0,0,0.0,17,...,0,0,0,0,0,27,102,0,0,0
6,Malsom Tuboi,0,0.0,0,0,0,0,0,0.0,3,...,0,0,0,0,0,6,102,0,0,0
7,Moosa Ashiq,0,0.0,0,0,0,1,0,0.0,55,...,0,0,0,0,0,96,102,0,0,0
8,Muhammed Ziyad K,0,0.0,0,0,1,2,1,0.0,22,...,0,0,0,0,0,32,102,0,0,0
9,Ngashepam Reoson Singh,0,0.0,1,1,0,3,2,0.0,93,...,0,0,0,0,0,98,102,0,0,0
10,Paoginmang Baite,0,0.0,0,0,0,2,0,0.0,45,...,1,1,0,0,0,94,102,0,0,0
11,Raj Singh Wahengbam,1,0.0,1,1,0,4,2,0.0,42,...,0,0,0,0,0,61,102,0,0,0
12,Rokash Atom,0,0.0,0,1,0,2,2,0.0,79,...,0,0,0,0,0,96,102,0,0,0
13,Sailex Oinam,0,0.0,0,0,0,0,0,0.0,52,...,0,0,0,0,0,98,102,0,0,0
14,Thangkhanlam Samte,0,0.0,0,1,2,5,0,0.0,89,...,0,0,0,0,0,97,102,0,0,0

In [67]:
network_metrics_df1 = main.calculate_network_metrics(team1)
network_metrics_df2 = main.calculate_network_metrics(team2)
network_metrics_df2

,Jersey,degree_centrality,betweenness_centrality,closeness_centrality,flow_centrality,flow_success,betweenness2goals
19.0,19,1.000000,0.129827,0.603571,0.175196,0.0,0.0
4.0,4,0.928571,0.035322,0.548701,0.142975,0.0,0.0
1.0,1,0.285714,0.000000,0.482857,0.000000,0.0,0.0
3.0,3,1.000000,0.096795,0.603571,0.140529,0.0,0.0
7.0,7,0.642857,0.004487,0.502976,0.000000,0.0,0.0
11.0,11,0.571429,0.002198,0.574830,0.000000,0.0,0.0
50.0,50,1.571429,0.184314,0.710084,0.054029,0.0,0.0
5.0,5,1.214286,0.055141,0.670635,0.011905,0.0,0.0
34.0,34,0.357143,0.001099,0.464286,0.007326,0.0,0.0
22.0,22,1.000000,0.063566,0.603571,0.099895,0.0,0.0
2.0,2,1.357143,0.096389,0.603571,0.260701,0.0,0.0
9.0,9,0.714286,0.024542,0.548701,0.072527,0.0,0.0
8.0,8,0.714286,0.011447,0.574830,0.047488,0.0,0.0
44.0,44,0.571429,0.075092,0.502976,0.083019,0.0,0.0
14.0,14,0.071429,0.000000,0.368421,0.000000,0.0,0.0

In [68]:
player_net_metrics1 = main_minerva.unique_jerseys(team1, network_metrics_df1)
player_net_metrics1

,Jersey,degree_centrality,betweenness_centrality,closeness_centrality,flow_centrality,flow_success,betweenness2goals,Player
0,9,0.769231,0.119979,0.500000,0.113141,0.0,0.0,Gunleiba Wangkheirakpam
1,4,0.923077,0.120726,0.650000,0.087607,0.0,0.0,Shubham Poonia
2,22,0.230769,0.004274,0.481481,0.000000,0.0,0.0,Mahesh Meitei
3,11,0.692308,0.043376,0.481481,0.061966,0.0,0.0,Thongbam Singh
4,18,0.692308,0.103846,0.448276,0.077885,0.0,0.0,Naorem Singh
5,3,1.153846,0.329380,0.722222,0.432265,0.0,0.0,Telem Singh
6,5,0.538462,0.043269,0.500000,0.029167,0.0,0.0,Suraj Murmu
7,6,0.615385,0.047436,0.500000,0.007372,0.0,0.0,Khuraijam Meetei
8,1,0.384615,0.070513,0.500000,0.072650,0.0,0.0,Aadil
9,14,0.230769,0.009615,0.464286,0.049038,0.0,0.0,Wangkheirakpam Meitei
10,8,0.923077,0.190919,0.565217,0.288355,0.0,0.0,Samuel Hakoip
11,8,0.923077,0.190919,0.565217,0.288355,0.0,0.0,Samuel Haokip
12,11,0.692308,0.043376,0.481481,0.061966,0.0,0.0,Thogbam singh
13,7,0.076923,0.000000,0.000000,0.000000,0.0,0.0,Heman Meitei
14,2,0.230769,0.006410,0.419355,0.007479,0.0,0.0,Karambir Singh
15,12,0.230769,0.000000,0.406250,0.000000,0.0,0.0,Laishram Singh

In [82]:
player_net_metrics1 = main_minerva.unique_jerseys(team1, network_metrics_df1)
player_net_metrics2 = main_minerva.unique_jerseys(team2, network_metrics_df2)
def final_df(network_stats_df, player_stats_df):
    final_df = network_stats_df.merge(player_stats_df, on='Player', how='left')
    final_df.drop(columns =['Jersey'])
    final_df = final_df[['Player','goals', 'assists', 'shots_ontarget',
       'shots_offtarget', 'shotsblocked', 'drib_success', 'drib_unsuccess',
       'keypasses', 'touches', 'passes_acc', 'passes_inacc', 'lballs_acc',
       'lballs_inacc', 'grduels_w', 'grduels_l', 'aerials_w', 'aerials_l',
       'fouls', 'clearances', 'interceptions', 'tackles', 'dribbled_past',
       'tballs_acc', 'tballs_inacc', 'ycards', 'rcards', 'offsides',
       'saved_pen', 'missed_penalties', 'owngoals', 'degree_centrality',
       'betweenness_centrality', 'closeness_centrality', 'flow_centrality',
       'flow_success', 'betweenness2goals', 'win', 'lost', 'is_home_team',
       'minutesPlayed', 'game_duration', 'crosses_att', 'saves_made',
       'goals_conceded']]
    return final_df

input_df1 = final_df(player_net_metrics1, player_stats1 )
input_df2 = final_df(player_net_metrics2, player_stats2)
input_df2.columns

Index(['Player', 'goals', 'assists', 'shots_ontarget', 'shots_offtarget',
       'shotsblocked', 'drib_success', 'drib_unsuccess', 'keypasses',
       'touches', 'passes_acc', 'passes_inacc', 'lballs_acc', 'lballs_inacc',
       'grduels_w', 'grduels_l', 'aerials_w', 'aerials_l', 'fouls',
       'clearances', 'interceptions', 'tackles', 'dribbled_past', 'tballs_acc',
       'tballs_inacc', 'ycards', 'rcards', 'offsides', 'saved_pen',
       'missed_penalties', 'owngoals', 'degree_centrality',
       'betweenness_centrality', 'closeness_centrality', 'flow_centrality',
       'flow_success', 'betweenness2goals', 'win', 'lost', 'is_home_team',
       'minutesPlayed', 'game_duration', 'crosses_att', 'saves_made',
       'goals_conceded'],
      dtype='object')

In [84]:
input_df2

,Player,goals,assists,shots_ontarget,shots_offtarget,shotsblocked,drib_success,drib_unsuccess,keypasses,touches,...,flow_success,betweenness2goals,win,lost,is_home_team,minutesPlayed,game_duration,crosses_att,saves_made,goals_conceded
0,Loitam Mangal Singh,0,0.0,0,0,0,0,0,0.0,17,...,0.0,0.0,0,0,0,27,102,0,0,0
1,Jayed,0,0.0,0,0,0,4,1,0.0,59,...,0.0,0.0,0,0,0,73,102,1,0,0
2,Sailex Oinam,0,0.0,0,0,0,0,0,0.0,52,...,0.0,0.0,0,0,0,98,102,0,0,0
3,Khwairakpam Yoihenba,0,0.0,0,0,0,0,0,0.0,29,...,0.0,0.0,0,0,0,95,102,0,1,1
4,Moosa Ashiq,0,0.0,0,0,0,1,0,0.0,55,...,0.0,0.0,0,0,0,96,102,0,0,0
5,Lairenjam Sanathoi Meitei,0,0.0,0,0,0,6,0,0.0,43,...,0.0,0.0,0,0,0,66,102,5,0,0
6,Khangembem Gibash Meitei,0,0.0,0,0,1,4,1,0.0,33,...,0.0,0.0,0,0,0,26,102,1,0,0
7,Thangkhanlam Samte,0,0.0,0,1,2,5,0,0.0,89,...,0.0,0.0,0,0,0,97,102,1,0,0
8,Rokash Atom,0,0.0,0,1,0,2,2,0.0,79,...,0.0,0.0,0,0,0,96,102,2,0,0
9,Ngashepam Reoson Singh,0,0.0,1,1,0,3,2,0.0,93,...,0.0,0.0,0,0,0,98,102,0,0,0
10,Paoginmang Baite,0,0.0,0,0,0,2,0,0.0,45,...,0.0,0.0,0,0,0,94,102,0,0,0
11,Ahvas K,0,0.0,0,0,0,2,2,0.0,43,...,0.0,0.0,0,0,0,66,102,2,0,0
12,Raj Singh Wahengbam,1,0.0,1,1,0,4,2,0.0,42,...,0.0,0.0,0,0,0,61,102,1,0,0
13,Muhammed Ziyad K,0,0.0,0,0,1,2,1,0.0,22,...,0.0,0.0,0,0,0,32,102,1,0,0
14,Malsom Tuboi,0,0.0,0,0,0,0,0,0.0,3,...,0.0,0.0,0,0,0,6,102,0,0,0

In [46]:
player_net_metrics2

,Jersey,degree_centrality,betweenness_centrality,closeness_centrality,flow_centrality,flow_success,betweenness2goals,Player
0,34,0.357143,0.001099,0.464286,0.007326,0.0,0.0,Loitam Mangal Singh
1,19,1.000000,0.129827,0.603571,0.175196,0.0,0.0,Jayed
2,4,0.928571,0.035322,0.548701,0.142975,0.0,0.0,Sailex Oinam
3,1,0.285714,0.000000,0.482857,0.000000,0.0,0.0,Khwairakpam Yoihenba
4,3,1.000000,0.096795,0.603571,0.140529,0.0,0.0,Moosa Ashiq
5,7,0.642857,0.004487,0.502976,0.000000,0.0,0.0,Lairenjam Sanathoi Meitei
6,11,0.571429,0.002198,0.574830,0.000000,0.0,0.0,Khangembem Gibash Meitei
7,50,1.571429,0.184314,0.710084,0.054029,0.0,0.0,Thangkhanlam Samte
8,5,1.214286,0.055141,0.670635,0.011905,0.0,0.0,Rokash Atom
9,2,1.357143,0.096389,0.603571,0.260701,0.0,0.0,Ngashepam Reoson Singh
10,22,1.000000,0.063566,0.603571,0.099895,0.0,0.0,Paoginmang Baite
11,8,0.714286,0.011447,0.574830,0.047488,0.0,0.0,Ahvas K
12,9,0.714286,0.024542,0.548701,0.072527,0.0,0.0,Raj Singh Wahengbam
13,44,0.571429,0.075092,0.502976,0.083019,0.0,0.0,Muhammed Ziyad K
14,14,0.071429,0.000000,0.368421,0.000000,0.0,0.0,Malsom Tuboi